### PR TITLE
Make "column"-property of Errors enumerable

### PR DESCRIPTION
**Pull request by nknapp**
This PR contains a test case for #1284. It verifies that the column-property is included in the compilation error. The test passes. This is not mean to be merged right now, primarily for discussion.

### CODE REVIEW

**Comment by nknapp** [comment]
I have reworded my commit messages and would not consider this work-in-progress anymore. If all tests pass and this PR does not introduce another regression (I have no Safari to test the bug fixed in 20c965c), it could be merged (from my point of view) and it would probably help @nathanboktae a lot if there was a 4.0.7 release including this PR.

@kpdecker @lawnsea @ErisDS @wycats

**Comment by nathanboktae** [comment]
> I have no Safari to test

That's what SauceLabs is for right? I'm not seeing right off hand if Travis CI is kicking off tests in SauceLabs

**Comment by nknapp** [comment]
@wycats gave me commit access tonight. I have created a local branch "tmp/stage-4.0.7" and push the changes there. This should run the tests in SauceLabs and show any Safari-problems.

**Comment by nknapp** [comment]
Tests case failing for Safari 8: ['97' should === '5': Checking error column"](https://github.com/wycats/handlebars.js/pull/1285/commits/7a51fa7cb24bc77b2e9c555619d34f6c11a50c94#diff-49874fc4bd5a81e1ceb0e8d284ee8c8bR46).

Why should Safari 8 return a completely different column than all other browsers?

**Comment by nknapp** [comment]
Ah, that's why: https://github.com/jquery/esprima/issues/1290#issuecomment-132455482

**Comment by nknapp** [comment]
The column-property is read-only in Safari 8, its value won't change, even with Object.defineProperty. The test case now omits the column-check, if the property is read-only.
